exp_name: debug
phase_config: configs\sampler\baseline_sampler.yaml
n_steps: 1000
batch_size: 16
lr: 0.0001
gradient_accumulation_steps: 4
cfg_scale: 2.0
cfg_ratio: 0.1
log_interval: 100
save_interval: 100
image_size: 28
channels: 1
jvp_api: funtorch
sample_steps:
- 1
- 5
